### ISSUE TITLE
Product-Feed is not working

### ISSUE THREAD

**Issue by falco-knapp** [Inxmail/inx_magento2#69]
Environment:
Magento ver. 2.3.4
Inxmail Module Version: 1.1.1

Trying to retrieve product data leads to an HTTP 500 Error:

http://consol-test.inxmail.com/breathe-easy-tank.html
http://consol-test.inxmail.com/inxmail/rest/products/WT09

"Fatal Error: 'Uncaught TypeError: strpos() expects parameter 1 to be string, null given in \/var\/www\/html\/vendor\/magento\/module-theme\/Controller\/Result\/JsFooterPlugin.php:44\nStack trace:\n#0 \/var\/www\/html\/vendor\/magento\/module-theme\/Controller\/Result\/JsFooterPlugin.php(44): strpos(NULL, '<\/body')\n#1 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(121): Magento\\Theme\\Controller\\Result\\JsFooterPlugin->beforeSendResponse(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#2 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\Response\\Http\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#3 \/var\/www\/html\/generated\/code\/Magento\/Framework\/App\/Response\/Http\/Interceptor.php(117): Magento\\Framework\\App\\Response\\Http\\Interceptor->___callPlugins('sendResponse', Array, Array)\n#4 \/var\/www\/html\/vendor\/magento\/framework\/App\/Bootstrap.php(262): Magento\\Framework\\App\\Response\\Http\\Interceptor->sendResponse()\n#5 \/var\/www\/html\/index.php(39): Magento\\Framework\\App\\Boot' in '\/var\/www\/html\/vendor\/magento\/module-theme\/Controller\/Result\/JsFooterPlugin.php' on line 44"

**Comment by bjoern-flagbit** [comment]
Hey Falco this looks like a core bug. Check this issue here:
https://github.com/magento/magento2/issues/25438

Should we do something here?

**Comment by falco-knapp** [comment]
hmmm ... as far as I understood it there is already a fix. However, it is not yet released.

The fix however is in "app/code/Magento/Theme/Controller/Result/JsFooterPlugin.php " 

How does this affect the Magento 2 REST-API that we are using?

**Comment by bjoern-flagbit** [comment]
The JsFooterPlugin has a Plugin that is called on beforeSendResponse ... so Inxmail Controller for the Rest API is using the Magento2 \Magento\Framework\Webapi\Rest\Response Class and the Plugin is fired before the "sendRepsonse" function is executed. And because of that the "getContent" Function is not getting a string back more less it is getting NULL back why then this error is thrown.

The JsFooterPlugin is one this class App/Response/Http.php and the  \Magento\Framework\Webapi\Rest\Response extends Magento\Framework\Webapi\Response and this implements \Magento\Framework\App\Response\HttpInterface and this extends \Magento\Framework\App\ResponseInterface ... so this is a big chain.

The only more less easy solution to be independent is to create a plugin with a higher sort order that will prevent all other plugins from execution on sendRepsonse function ONLY for our inxmail rest api controller.

**Comment by falco-knapp** [comment]
worked on Magento 2.4.3-p1
